// https://developer.android.com/jetpack/compose/performance/stability/fix#configuration-file

// Kotlin Immutable Collections
kotlinx.collections.immutable.*

kotlin.uuid.*
kotlin.time.*

// Java Time
java.time.*

app.amber.ai.ui.UIMessageAnnotation
app.amber.ai.ui.ToolApprovalState
app.amber.ai.core.TokenUsage
