package app.amber.feature.ui.components.richtext.tree

import android.app.Application
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithTag
import app.amber.agent.ui.components.richtext.nativebridge.PackedAstReader
import app.amber.core.settings.Settings
import app.amber.feature.ui.components.richtext.MarkdownParseResult
import app.amber.feature.ui.components.richtext.MarkdownTreeForParityTest
import app.amber.feature.ui.components.richtext.parseRawMarkdownForParityTest
import app.amber.feature.ui.context.LocalNavController
import app.amber.feature.ui.context.LocalSettings
import app.amber.feature.ui.context.Navigator
import app.amber.highlight.Highlighter
import app.amber.highlight.LocalHighlighter
import kotlinx.coroutines.CoroutineExceptionHandler
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.ParameterizedRobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import org.robolectric.annotation.Config
import org.robolectric.annotation.GraphicsMode
import java.io.File

/**
 * TD.Rust.1a Phase 3-B — the dual-render PARITY rig. Renders the SAME markdown TWICE through the
 * SAME production renderer — once driven by the JetBrains JVM tree ([JvmMdNode]), once by the
 * packed-AST native tree ([NativeMdNode]) — and asserts the two semantics dumps match. The renderer
 * is the constant; the tree engine is the only variable. This is the final proof of whether the
 * Stage-4 tree switch is render-safe.
 *
 * ## What it proves (and how it differs from the sibling tests)
 *  - [NativeMdTreeTest] pins the native tree's *accessors* against the mapping doc.
 *  - [MarkdownRendererSnapshotTest] pins the JVM render output against a golden text dump.
 *  - THIS test compares JVM-tree render vs native-tree render of identical input. Equal dumps for a
 *    sample ⇒ the renderer is engine-agnostic for that input. Unequal dumps ⇒ a real renderer
 *    divergence the `markdownAst` flag must not ship over.
 *
 * ## Seam chosen: [MarkdownTreeForParityTest] — render a pre-built result through MarkdownBlock's
 * non-streaming dispatch
 * A Compose test rule permits exactly ONE `setContent`, so the two trees must render in the SAME
 * composition. They cannot both go through `MarkdownBlock(content)` because that entry re-derives the
 * tree from the shared parse cache (one key per content), so both calls would get the same tree.
 * Markdown.kt instead exposes [MarkdownTreeForParityTest], a thin `@VisibleForTesting` composable
 * that runs the EXACT render dispatch `MarkdownBlock` reaches on a settled (non-streaming) result —
 * the `else` arm walking `result.tree.children` via the private `MarkdownNode`, or the identical
 * `MarkdownNew(content)` HTML arm. For a settled result every streaming CompositionLocal already
 * equals its default, so this is render-equivalent to `MarkdownBlock(content)`. Both engines run this
 * ONE composable; the ONLY variable is which [MdNode] tree the result carries. We render both
 * side-by-side under distinct `testTag`s and dump each subtree separately.
 *
 * ## Input alignment: tree-vs-tree on identical RAW text
 * The golden `.pmda` blobs were generated by `dump_corpus` from the RAW `.md` text (no preprocessing
 * — see [NativeMdTreeTest] KDoc). The production funnel parses PREPROCESSED text (`preProcess()` =
 * KaTeX delimiter conversion + bare-URL linkify), but preprocessing is UPSTREAM of the parse and
 * applies EQUALLY to both engines at runtime — it does not distinguish JVM from native. So for a
 * like-for-like tree comparison both paths are fed the same RAW text:
 *  - JVM tree: [parseRawMarkdownForParityTest] runs the JetBrains parse on raw text, bypassing
 *    `preProcess` exactly as the native blob did.
 *  - Native tree: [PackedAstReader] over the golden blob + [nativeMdTreeOrNull] against raw text.
 * This is tree-vs-tree parity on identical input; production preprocessing is engine-neutral.
 *
 * ## ACCEPTED divergence — narrow, cited normalization (controller ruling)
 *  - **Image alt brackets** — the JVM `linkLabel` includes the surrounding `[ ]`; the native
 *    concatenated label does not (NativeMdTree.kt `linkLabel` KDoc + spec review). Image alt surfaces
 *    in the dump as `image=<contentDescription>`, so [normalizeImageAltBrackets] strips a single
 *    leading `[` / trailing `]` from `image=` segments on both sides before comparison. This is the
 *    ONLY normalization applied — never blanket fuzzy matching.
 *  - **`[X]` uppercase task checkbox** — native = checked, JVM = unchecked (controller-accepted GFM
 *    fix; NativeMdTree.kt `taskChecked` KDoc). The semantics dump does NOT surface checkbox state
 *    (see [dumpNormalized] "does NOT capture" list), so this divergence cannot perturb the dumps and
 *    needs no normalization.
 *
 * ## ✅ The two renderer bugs this rig discovered are now FIXED (T14.5 / td-rust-1a)
 * The rig originally surfaced two genuine bugs in the production renderer's tree walk. Both are now
 * fixed with SHAPE-AGNOSTIC renderer dispatch (Markdown.kt) — the trees stay honest to their parsers:
 *
 *  - **BUG #1 (FIXED) — native headings render EMPTY.** The Heading arm of `MarkdownNode` rendered
 *    ONLY children of type [MdNodeType.Paragraph] — the JetBrains `ATX_CONTENT → Paragraph` wrapper.
 *    The native tree has NO wrapper; its heading children are FLAT inline nodes, so the filter matched
 *    nothing. FIX: render the Paragraph wrapper child when present (JVM shape), else render the
 *    heading node itself through `Paragraph()` (native shape — `Paragraph` walks the flat inline
 *    children via `appendMarkdownNodeContent`). JVM golden output is byte-identical (one Paragraph
 *    child per heading → exactly one render either way; snapshot test stays 32/32).
 *  - **BUG #2 (FIXED) — native inline code keeps its backticks.** The generic leaf arm
 *    (`node.children.isEmpty()`) of `appendMarkdownNodeContent` PRECEDED the type-specific arms, so a
 *    childless native `InlineCode`/`MathInline` leaf hit it and was appended raw (backticks /
 *    `$formula$`) instead of dispatching by type. FIX: hoist the `InlineCode` + `MathInline` arms
 *    ABOVE the leaf arm (type-dispatch before shape-dispatch). Audit of every children-shape-gated
 *    arm: only those two inline types are childless in the native tree AND have an arm after the leaf
 *    arm; the Emphasis/Strong/Strikethrough/Link arms are inline CONTAINERS that always carry content
 *    children, so they never hit the leaf arm. JVM byte-identical (those JVM nodes carry marker-token
 *    children and never matched the leaf arm).
 *
 * ## ⚠ Residual classes UNMASKED once #1/#2 were fixed (DONE_WITH_CONCERNS — documented, skipped)
 * Fixing #1/#2 promoted 9 samples to hard parity but uncovered FIVE further divergence classes that
 * the two bugs had been masking. These are NOT the same class as #1/#2 — they are tree-/parser-level
 * differences (or a golden-locked JVM rendering quirk), so they are NOT fixable by renderer dispatch
 * without rewriting list grouping or REGENERATING the forbidden JVM goldens. They stay in
 * [KNOWN_DIVERGENT_SAMPLES], skipped and individually cited. The rot guard still re-promotes any that
 * later reach parity.
 *
 *  - **[A] Heading inline-token trim-space (golden-locked JVM quirk; native is faithful).** The JVM
 *    heading path renders inline content via `Paragraph(trim=true)`; the JetBrains tree splits heading
 *    text into multiple TEXT tokens at punctuation (em-dash / `(` / `"` / `:`), and each token is
 *    `.trim()`'d, dropping the interior spaces. `## GFM Tables — Simple` → JVM `Tables—Simple` (the
 *    GOLDEN snapshot pins this), native `Tables — Simple` (single Text leaf, trimmed once). Native is
 *    arguably MORE correct, but the JVM behavior is locked by the goldens — un-fixable here.
 *  - **[B] Backslash-escape resolution.** JetBrains keeps `\_` / `\!` / `\(` literally in the text
 *    slice; pulldown resolves the escape (`_` / `!` / `(`). Parser-level; not a renderer concern.
 *  - **[C] List-item inline-run grouping (FIXED — T14.6).** A TIGHT list item's inline content
 *    (`- Call `code` to…`) is a single grouped Text run on the JVM tree (a PARAGRAPH wrapper child)
 *    but FLAT inline children on the native tree (no Paragraph wrapper — same structural family as
 *    the old BUG #1, but in `ListItemNode`'s per-child loop). The old per-child loop rendered `Call`
 *    / `code` / `to…` as separate Text composables on the native shape. FIX (Markdown.kt): in
 *    `ListItemNode`, dispatch on shape — if the item's direct content contains a Paragraph wrapper
 *    (JVM) render per-child as before; otherwise (native flat inline) group the whole inline run
 *    through ONE `Paragraph()` via the render-time `InlineRunMdNode` view (children = the real flat
 *    inline nodes, nested lists excluded). JVM is byte-identical: the JVM branch is the unchanged
 *    original loop, and the snapshot suite (JVM-tree path) stays 32/32. Samples 10 + 13 promoted to
 *    hard parity; sample 24's [C] component is resolved too (it stays skipped only on the distinct
 *    [B-CJK] strong-emphasis class below).
 *  - **[B-CJK] CJK-flanked strong emphasis (parser-level; unmasked when [C] was fixed in 24).**
 *    Source `常被称为**"离线优先"**策略`: the JVM (JetBrains) tree forms a Strong node (renders bold,
 *    `**` stripped); the native (pulldown-cmark) tree does NOT match the `**` delimiter run when both
 *    flanks are CJK — CommonMark's left/right-flanking rules treat CJK as non-punctuation, so the run
 *    is simultaneously left- and right-flanking and fails to open/close — and emits literal `*` Text
 *    leaves instead. Verified at the TREE level (TREEDIAG): a Strong child on JVM vs bare `*` Text on
 *    native. Like [B], this is a parser disagreement in the renderer's INPUT, not a shape bug.
 *  - **[D] Link / autolink / footnote / reference text.** Email autolink `<x>` (JVM keeps the
 *    brackets, native resolves a mailto link), reference links `[t][ref]` (JVM literal, native
 *    resolved), footnote definitions `[^id]:` (JVM keeps the marker text). Tree-structure differences.
 *  - **[E] Soft-break leading whitespace.** A blockquote soft-break continuation line carries a
 *    leading space on the JVM tree, none on the native tree. Parser whitespace tokenization.
 *
 * All five are in the SHARED renderer's INPUT (the tree), not its shape-dispatch, so the
 * `markdownAst` flag must stay default-false until [C] (renderer-fixable) and [A]/[B]/[D]/[E]
 * (tree-fixable) are resolved. See the T14.5 handoff parity report for the full breakdown.
 *
 * Robolectric scaffolding (config / theme / locals / async-load handler) mirrors
 * [MarkdownRendererSnapshotTest] verbatim — a parity gap is attributable to the tree, not the harness.
 */
@RunWith(ParameterizedRobolectricTestRunner::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
@Config(sdk = [34], application = Application::class)
class MarkdownTreeParityTest(
    private val sampleName: String,
    private val sampleFile: File,
) {

    // Same async-load swallow as the snapshot test: the QuickJS/Prism highlighter loads a native
    // `.so` absent on the host JVM, so HighlightText's off-thread highlight() resumes with an
    // UnsatisfiedLinkError (possibly wrapped). The dumped code Text is the raw source either way, so
    // we swallow it in the compose effect context rather than crash waitForIdle().
    private val swallowAsyncLoadFailures = CoroutineExceptionHandler { _, t ->
        if (generateSequence<Throwable>(t) { it.cause }.none { it is UnsatisfiedLinkError }) {
            throw t
        }
    }

    @get:Rule
    val compose = createComposeRule(swallowAsyncLoadFailures)

    @Test
    fun nativeTreeRendersEquivalentlyToJvmTree() {
        val rawText = sampleFile.readText()
        val blob = blobFileFor(sampleName).readBytes()

        // ── JVM tree over RAW text (JetBrains parse, preProcess bypassed) ──
        val jvmResult = parseRawMarkdownForParityTest(rawText)

        // ── Native tree over the SAME RAW text, from the golden blob (no JNI on host) ──
        val reader = PackedAstReader(blob)
        assertTrue("$sampleName: golden blob invalid — regen corpus", reader.isValid && reader.validate())
        val nativeRoot = nativeMdTreeOrNull(reader, rawText)
            ?: throw AssertionError("$sampleName: native tree had no decodable root")
        val nativeResult = MarkdownParseResult(
            preprocessed = rawText,
            tree = nativeRoot,
            hasHtmlBlocks = reader.hasHtmlBlocks,
        )

        // hasHtmlBlocks MUST agree: if it didn't, one engine would route to MarkdownNew (HTML
        // re-parse) and the other to the tree path — a structural divergence, not a render nit.
        // The blob-header bit and JVM containsHtmlBlocks() are designed to match (Markdown.kt
        // parsePreprocessedMarkdownUncached KDoc). Assert it so a regression surfaces loudly.
        assertEquals(
            "$sampleName: hasHtmlBlocks disagree (JVM=${jvmResult.hasHtmlBlocks} " +
                "native=${nativeResult.hasHtmlBlocks}) — would split the render path",
            jvmResult.hasHtmlBlocks,
            nativeResult.hasHtmlBlocks,
        )

        // Render BOTH engines in one composition (a Compose test rule allows only one setContent),
        // each under a distinct testTag so we can dump the two subtrees independently.
        val highlighter = Highlighter(RuntimeEnvironment.getApplication())
        compose.setContent {
            CompositionLocalProvider(
                LocalSettings provides Settings(),
                LocalNavController provides Navigator(mutableListOf()),
                LocalHighlighter provides highlighter,
            ) {
                MaterialTheme {
                    Column {
                        Box(Modifier.testTag(TAG_JVM)) {
                            MarkdownTreeForParityTest(content = rawText, result = jvmResult)
                        }
                        Box(Modifier.testTag(TAG_NATIVE)) {
                            MarkdownTreeForParityTest(content = rawText, result = nativeResult)
                        }
                    }
                }
            }
        }
        compose.waitForIdle()

        // dumpNormalized ignores the TestTag property (it captures only Text/ContentDescription/
        // Role/Image/links), so the tagged Box contributes no dump line — only its rendered subtree.
        val jvmDump = compose.onNodeWithTag(TAG_JVM).fetchSemanticsNode().dumpNormalized()
        val nativeDump = compose.onNodeWithTag(TAG_NATIVE).fetchSemanticsNode().dumpNormalized()

        val jvmNorm = jvmDump.normalizeImageAlt()
        val nativeNorm = nativeDump.normalizeImageAlt()
        val parity = jvmNorm == nativeNorm

        if (sampleName in KNOWN_DIVERGENT_SAMPLES) {
            // Rot guard: a known-divergent sample that now MATCHES means a renderer fix landed —
            // promote it back to a hard-parity sample so the proof tightens.
            if (parity) {
                throw AssertionError(
                    "$sampleName now renders at parity — remove it from KNOWN_DIVERGENT_SAMPLES " +
                        "(its documented residual divergence class [A]/[B]/[C]/[D]/[E] appears fixed).",
                )
            }
            // Still divergent as documented — skip loudly (visible as SKIPPED, never a false PASS).
            assumeTrue(
                "$sampleName diverges due to a documented residual tree-/parser-level class " +
                    "([A] heading trim-space / [B] escape resolution / [C] list-item grouping / " +
                    "[D] link-footnote text / [E] soft-break whitespace — see class KDoc + parity " +
                    "report). BUG #1 (heading-drop) and BUG #2 (inline-code-backtick) are FIXED; " +
                    "these residuals must be resolved before markdownAst can flip on.",
                false,
            )
        }

        // Non-divergent sample: assert HARD parity.
        if (!parity) {
            throw AssertionError(buildParityDiff(sampleName, jvmNorm, nativeNorm))
        }
    }

    private fun String.normalizeImageAlt(): String =
        lines().joinToString("\n") { it.normalizeImageAltBrackets() }

    companion object {
        private val CORPUS_DIR = File(MARKDOWN_CORPUS_DIR)
        private const val TAG_JVM = "parity-jvm-tree"
        private const val TAG_NATIVE = "parity-native-tree"

        /**
         * Samples whose JVM-tree and native-tree renders STILL diverge after BUG #1 (heading-drop)
         * and BUG #2 (inline-code-backtick) were fixed. Each remaining sample is tagged with the
         * residual class [A]…[E] documented in the class KDoc — these are tree-/parser-level or
         * golden-locked differences, NOT the renderer-shape-dispatch bugs T14.5 addressed. They are
         * SKIPPED (not failed, not passed) so the suite is green WITHOUT pretending the native tree
         * renders correctly — and the rot guard re-promotes any that later reach parity. Samples that
         * are NOW (or were always) at hard parity are NOT here:
         *  - 01, 02, 07, 08, 09, 21, 26 — promoted to hard parity by the BUG #1/#2 fixes.
         *  - `20-html-block` — `hasHtmlBlocks`, both engines route to the identical `MarkdownNew`
         *    HTML path, so the tree is bypassed (trivially equal, but a real datapoint: the HTML
         *    arm is parity-safe).
         *  - `30-empty-and-whitespace` — whitespace-only input, both render nothing.
         */
        private val KNOWN_DIVERGENT_SAMPLES: Set<String> = setOf(
            // BUG #1 (native-heading-drop) and BUG #2 (native-inline-code-backtick) are FIXED
            // (shape-agnostic heading + inline-leaf dispatch, Markdown.kt). 9 samples that diverged
            // SOLELY on those two bugs now render at hard parity and have left this list:
            //   01, 02, 07, 08, 09, 21, 26 (plus 20-html-block / 30-empty, never listed).
            // The samples that REMAIN here diverge on the residual tree-/parser-level classes the
            // two bug-fixes UNMASKED (see class KDoc §"residual classes"). These are NOT
            // renderer-shape-dispatch bugs fixable without either rewriting list-item/loose grouping
            // or changing the JVM golden snapshots (forbidden), so they stay skipped and cited. Tag
            // legend: [A] heading inline-token trim-space (golden-locked JVM quirk; native faithful),
            // [B] backslash-escape resolution, [C] list-item inline-run grouping, [D] link/autolink/
            // footnote/reference text, [E] soft-break leading whitespace.
            "03-emphasis-nesting",        // [B] `middle\_of\_a\_word` (JVM keeps `\_`, native strips)
            "04-links-inline",            // [D] email autolink `<x>` kept by JVM, resolved by native
            "05-links-with-titles",       // [D] reference link `[t][ref]` literal (JVM) vs resolved
            "06-images",                  // [D] inline-image run split differs between trees
            // 10-inline-code, 13-nested-lists: class [C] (list-item inline-run grouping) RESOLVED by
            // the shape-agnostic ListItemNode dispatch (Markdown.kt InlineRunMdNode) — both now render
            // at hard parity and have left this list.
            "11-gfm-table-simple",        // [A] heading `Tables — Simple` → JVM `Tables—Simple`
            "12-gfm-table-aligned",       // [A] heading em-dash trim-space
            "14-ordered-list-start",      // [A] heading em-dash trim-space
            "15-task-lists",              // [A] heading `Task Lists (GFM…` → JVM `Task Lists(GFM…`
            "16-blockquotes-nested",      // [A] heading em-dash trim-space
            "17-thematic-breaks",         // [A] heading `Breaks (Horizontal…` paren trim-space
            "18-katex-inline",            // [A] heading em-dash trim-space
            "19-katex-block",             // [A] heading em-dash trim-space
            "22-footnotes",               // [D] footnote def `[^id]:` text kept (JVM) vs stripped
            "23-strikethrough",           // [A] heading `(GFM Extension)` paren trim-space
            // 24-cjk-mixed: the [C] list-item inline-run split is now RESOLVED (its list items render
            // at parity via the shape-agnostic dispatch). A DISTINCT residual remains and keeps it
            // here: [B-CJK] CJK-flanked strong emphasis. Source `常被称为**"离线优先"**策略` — the JVM
            // (JetBrains) tree forms a Strong node (renders bold, markers stripped); the native
            // (pulldown-cmark) tree does NOT match the `**` delimiter run when both flanks are CJK
            // (CommonMark left/right-flanking rules treat CJK as non-punctuation, so the run is both
            // left- and right-flanking and fails to open/close), emitting literal `*` Text leaves.
            // Verified at the TREE level (parity-test TREEDIAG): JVM paragraph has a Strong child,
            // native paragraph has bare `*`/`*` Text children — a parser-level divergence in the
            // renderer's INPUT, NOT a renderer-shape bug. Same family as [B] backslash-escape (the two
            // parsers resolve the same source differently), not [C].
            "24-cjk-mixed",               // [B-CJK] `**"离线优先"**` strong (JVM) vs literal `**` (native)
            "25-long-message",            // [A] heading `What is "Offline-First"?` quote trim-space
            "27-hard-soft-breaks",        // [E] blockquote soft-break continuation leading-space
            "28-link-edge-cases",         // [B]+[D] escaped-paren URL `path\(1\)` literal vs resolved
            "29-mixed-everything",        // [A] heading `Overview: AmberAgent` colon trim-space
            "31-deep-nesting",            // [A] heading `Paragraph + Code + …` trim-space
            "32-special-chars-escapes",   // [B] escapable-char run `\! \#…` kept (JVM) vs stripped
        )

        private fun blobFileFor(sampleName: String): File = File(CORPUS_DIR, "$sampleName.pmda")

        @JvmStatic
        @ParameterizedRobolectricTestRunner.Parameters(name = "{0}")
        fun samples(): List<Array<Any>> =
            CORPUS_DIR.listFiles { f -> f.extension == "md" }
                .orEmpty()
                // Only samples that have a paired golden blob can be compared tree-vs-tree.
                .filter { File(CORPUS_DIR, "${it.nameWithoutExtension}.pmda").exists() }
                .sortedBy { it.name }
                .map { arrayOf(it.nameWithoutExtension, it) }

        /**
         * ACCEPTED divergence #1 (image alt brackets). The dump renders image alt text as
         * `image=<contentDescription>`. The JVM tree's image alt is the RAW LINK_TEXT including the
         * surrounding `[ ]` (NativeMdTree.kt `linkLabel` KDoc: "the image-alt call site uses the
         * label as-is … native alt text lacks the brackets the JVM alt carries"). The bracket
         * presence is non-visible accessibility metadata, so we strip ONE leading `[` and ONE
         * trailing `]` from the alt segment of `image=` lines on both sides before comparison.
         */
        private fun String.normalizeImageAltBrackets(): String {
            val marker = "image="
            val idx = indexOf(marker)
            if (idx < 0) return this
            val prefix = substring(0, idx + marker.length)
            var alt = substring(idx + marker.length)
            if (alt.startsWith("[")) alt = alt.substring(1)
            if (alt.endsWith("]")) alt = alt.substring(0, alt.length - 1)
            return prefix + alt
        }

        /** Unified-ish diff between the two engines plus the first differing line. */
        private fun buildParityDiff(name: String, jvm: String, native: String): String {
            val j = jvm.lines()
            val n = native.lines()
            val firstDiff = (0 until maxOf(j.size, n.size)).firstOrNull {
                j.getOrNull(it) != n.getOrNull(it)
            }
            val pointer = if (firstDiff != null) {
                "\nfirst diff at line ${firstDiff + 1}:\n" +
                    "  jvm:    ${j.getOrNull(firstDiff)}\n" +
                    "  native: ${n.getOrNull(firstDiff)}"
            } else {
                ""
            }
            return buildString {
                appendLine("dual-tree render parity mismatch for sample '$name'")
                appendLine("(JVM JetBrains tree vs native packed-AST tree, same renderer, same raw input)")
                appendLine("If this is one of the two DOCUMENTED renderer bugs (native heading-drop /")
                appendLine("native inline-code-backtick), add '$name' to KNOWN_DIVERGENT_SAMPLES with a")
                appendLine("citation. If it is a NEW divergence, investigate the root cause first.")
                appendLine(pointer)
                appendLine("----- JVM TREE DUMP -----")
                appendLine(jvm)
                appendLine("----- NATIVE TREE DUMP -----")
                appendLine(native)
            }
        }
    }
}
