package app.amber.feature.ui.components.richtext.tree

import android.app.Application
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithTag
import app.amber.agent.ui.components.richtext.nativebridge.PackedAstReader
import app.amber.core.settings.Settings
import app.amber.feature.ui.components.richtext.MarkdownParseResult
import app.amber.feature.ui.components.richtext.MarkdownTreeForParityTest
import app.amber.feature.ui.components.richtext.parseRawMarkdownForParityTest
import app.amber.feature.ui.context.LocalNavController
import app.amber.feature.ui.context.LocalSettings
import app.amber.feature.ui.context.Navigator
import app.amber.highlight.Highlighter
import app.amber.highlight.LocalHighlighter
import kotlinx.coroutines.CoroutineExceptionHandler
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.ParameterizedRobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import org.robolectric.annotation.Config
import org.robolectric.annotation.GraphicsMode
import java.io.File

/**
 * TD.Rust.1a Phase 3-B — the dual-render PARITY rig. Renders the SAME markdown TWICE through the
 * SAME production renderer — once driven by the JetBrains JVM tree ([JvmMdNode]), once by the
 * packed-AST native tree ([NativeMdNode]) — and asserts the two semantics dumps match. The renderer
 * is the constant; the tree engine is the only variable. This is the final proof of whether the
 * Stage-4 tree switch is render-safe.
 *
 * ## What it proves (and how it differs from the sibling tests)
 *  - [NativeMdTreeTest] pins the native tree's *accessors* against the mapping doc.
 *  - [MarkdownRendererSnapshotTest] pins the JVM render output against a golden text dump.
 *  - THIS test compares JVM-tree render vs native-tree render of identical input. Equal dumps for a
 *    sample ⇒ the renderer is engine-agnostic for that input. Unequal dumps ⇒ a real renderer
 *    divergence the `markdownAst` flag must not ship over.
 *
 * ## Seam chosen: [MarkdownTreeForParityTest] — render a pre-built result through MarkdownBlock's
 * non-streaming dispatch
 * A Compose test rule permits exactly ONE `setContent`, so the two trees must render in the SAME
 * composition. They cannot both go through `MarkdownBlock(content)` because that entry re-derives the
 * tree from the shared parse cache (one key per content), so both calls would get the same tree.
 * Markdown.kt instead exposes [MarkdownTreeForParityTest], a thin `@VisibleForTesting` composable
 * that runs the EXACT render dispatch `MarkdownBlock` reaches on a settled (non-streaming) result —
 * the `else` arm walking `result.tree.children` via the private `MarkdownNode`, or the identical
 * `MarkdownNew(content)` HTML arm. For a settled result every streaming CompositionLocal already
 * equals its default, so this is render-equivalent to `MarkdownBlock(content)`. Both engines run this
 * ONE composable; the ONLY variable is which [MdNode] tree the result carries. We render both
 * side-by-side under distinct `testTag`s and dump each subtree separately.
 *
 * ## Input alignment: tree-vs-tree on identical RAW text
 * The golden `.pmda` blobs were generated by `dump_corpus` from the RAW `.md` text (no preprocessing
 * — see [NativeMdTreeTest] KDoc). The production funnel parses PREPROCESSED text (`preProcess()` =
 * KaTeX delimiter conversion + bare-URL linkify), but preprocessing is UPSTREAM of the parse and
 * applies EQUALLY to both engines at runtime — it does not distinguish JVM from native. So for a
 * like-for-like tree comparison both paths are fed the same RAW text:
 *  - JVM tree: [parseRawMarkdownForParityTest] runs the JetBrains parse on raw text, bypassing
 *    `preProcess` exactly as the native blob did.
 *  - Native tree: [PackedAstReader] over the golden blob + [nativeMdTreeOrNull] against raw text.
 * This is tree-vs-tree parity on identical input; production preprocessing is engine-neutral.
 *
 * ## ACCEPTED divergence — narrow, cited normalization (controller ruling)
 *  - **Image alt brackets** — the JVM `linkLabel` includes the surrounding `[ ]`; the native
 *    concatenated label does not (NativeMdTree.kt `linkLabel` KDoc + spec review). Image alt surfaces
 *    in the dump as `image=<contentDescription>`, so [normalizeImageAltBrackets] strips a single
 *    leading `[` / trailing `]` from `image=` segments on both sides before comparison. This is the
 *    ONLY normalization applied — never blanket fuzzy matching.
 *  - **`[X]` uppercase task checkbox** — native = checked, JVM = unchecked (controller-accepted GFM
 *    fix; NativeMdTree.kt `taskChecked` KDoc). The semantics dump does NOT surface checkbox state
 *    (see [dumpNormalized] "does NOT capture" list), so this divergence cannot perturb the dumps and
 *    needs no normalization.
 *
 * ## ⚠ REAL renderer divergences DISCOVERED by this rig (DONE_WITH_CONCERNS — NOT papered over)
 * Two genuine bugs in the production renderer's tree walk surfaced when fed the native tree. They are
 * REAL rendering differences (category b), so they are NOT normalized away. The affected samples are
 * listed in [KNOWN_DIVERGENT_SAMPLES] and SKIPPED (JUnit `assumeTrue`) with this citation — never
 * silently passed. The non-divergent samples assert HARD parity. A divergent sample that
 * UNEXPECTEDLY matches FAILS the rot guard ("remove it from KNOWN_DIVERGENT_SAMPLES"), so the
 * exclusion list cannot rot once a bug is fixed.
 *
 *  - **BUG #1 — native headings render EMPTY.** `MarkdownNode`'s Heading arm (Markdown.kt) iterates
 *    `node.children` and renders ONLY children whose type is [MdNodeType.Paragraph] — the JetBrains
 *    `ATX_CONTENT` wrapper (JvmMdTree.kt §4 H1: `ATX_CONTENT → Paragraph`). The native tree has NO
 *    such wrapper: its heading children are FLAT inline [MdNodeType.Text] nodes
 *    (NativeMdTreeTest.headingContentChildrenAreFlatInline). The `child.type == Paragraph` filter
 *    matches nothing → every native heading renders no text. Affects every sample with a heading.
 *  - **BUG #2 — native inline code keeps its backticks.** `appendMarkdownNodeContent`'s generic
 *    leaf arm `node.children.isEmpty()` (Markdown.kt) PRECEDES the `InlineCode` arm that does
 *    `textIn(content).trim('`')`. The JVM `InlineCode` node has child marker tokens, so it skips the
 *    leaf arm and reaches the trim. The native `InlineCode` is a childless LEAF
 *    (NativeMdTreeTest.inlineCodeTextInRoundTrip — its span includes the backticks), so it is caught
 *    by the leaf arm first and appended RAW (`` `code` `` with backticks) instead of trimmed.
 *
 * Both bugs are in the SHARED renderer (`MarkdownNode` / `appendMarkdownNodeContent`), so they would
 * affect production if the `markdownAst` flag flipped on — which is exactly why it stays default-false
 * pending dogfood. Fixing them is the renderer's job (Phase 3-B follow-up), not this rig's; the rig's
 * job is to surface them, which it does. See the task handoff parity report for the full breakdown.
 *
 * Robolectric scaffolding (config / theme / locals / async-load handler) mirrors
 * [MarkdownRendererSnapshotTest] verbatim — a parity gap is attributable to the tree, not the harness.
 */
@RunWith(ParameterizedRobolectricTestRunner::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
@Config(sdk = [34], application = Application::class)
class MarkdownTreeParityTest(
    private val sampleName: String,
    private val sampleFile: File,
) {

    // Same async-load swallow as the snapshot test: the QuickJS/Prism highlighter loads a native
    // `.so` absent on the host JVM, so HighlightText's off-thread highlight() resumes with an
    // UnsatisfiedLinkError (possibly wrapped). The dumped code Text is the raw source either way, so
    // we swallow it in the compose effect context rather than crash waitForIdle().
    private val swallowAsyncLoadFailures = CoroutineExceptionHandler { _, t ->
        if (generateSequence<Throwable>(t) { it.cause }.none { it is UnsatisfiedLinkError }) {
            throw t
        }
    }

    @get:Rule
    val compose = createComposeRule(swallowAsyncLoadFailures)

    @Test
    fun nativeTreeRendersEquivalentlyToJvmTree() {
        val rawText = sampleFile.readText()
        val blob = blobFileFor(sampleName).readBytes()

        // ── JVM tree over RAW text (JetBrains parse, preProcess bypassed) ──
        val jvmResult = parseRawMarkdownForParityTest(rawText)

        // ── Native tree over the SAME RAW text, from the golden blob (no JNI on host) ──
        val reader = PackedAstReader(blob)
        assertTrue("$sampleName: golden blob invalid — regen corpus", reader.isValid && reader.validate())
        val nativeRoot = nativeMdTreeOrNull(reader, rawText)
            ?: throw AssertionError("$sampleName: native tree had no decodable root")
        val nativeResult = MarkdownParseResult(
            preprocessed = rawText,
            tree = nativeRoot,
            hasHtmlBlocks = reader.hasHtmlBlocks,
        )

        // hasHtmlBlocks MUST agree: if it didn't, one engine would route to MarkdownNew (HTML
        // re-parse) and the other to the tree path — a structural divergence, not a render nit.
        // The blob-header bit and JVM containsHtmlBlocks() are designed to match (Markdown.kt
        // parsePreprocessedMarkdownUncached KDoc). Assert it so a regression surfaces loudly.
        assertEquals(
            "$sampleName: hasHtmlBlocks disagree (JVM=${jvmResult.hasHtmlBlocks} " +
                "native=${nativeResult.hasHtmlBlocks}) — would split the render path",
            jvmResult.hasHtmlBlocks,
            nativeResult.hasHtmlBlocks,
        )

        // Render BOTH engines in one composition (a Compose test rule allows only one setContent),
        // each under a distinct testTag so we can dump the two subtrees independently.
        val highlighter = Highlighter(RuntimeEnvironment.getApplication())
        compose.setContent {
            CompositionLocalProvider(
                LocalSettings provides Settings(),
                LocalNavController provides Navigator(mutableListOf()),
                LocalHighlighter provides highlighter,
            ) {
                MaterialTheme {
                    Column {
                        Box(Modifier.testTag(TAG_JVM)) {
                            MarkdownTreeForParityTest(content = rawText, result = jvmResult)
                        }
                        Box(Modifier.testTag(TAG_NATIVE)) {
                            MarkdownTreeForParityTest(content = rawText, result = nativeResult)
                        }
                    }
                }
            }
        }
        compose.waitForIdle()

        // dumpNormalized ignores the TestTag property (it captures only Text/ContentDescription/
        // Role/Image/links), so the tagged Box contributes no dump line — only its rendered subtree.
        val jvmDump = compose.onNodeWithTag(TAG_JVM).fetchSemanticsNode().dumpNormalized()
        val nativeDump = compose.onNodeWithTag(TAG_NATIVE).fetchSemanticsNode().dumpNormalized()

        val jvmNorm = jvmDump.normalizeImageAlt()
        val nativeNorm = nativeDump.normalizeImageAlt()
        val parity = jvmNorm == nativeNorm

        if (sampleName in KNOWN_DIVERGENT_SAMPLES) {
            // Rot guard: a known-divergent sample that now MATCHES means a renderer fix landed —
            // promote it back to a hard-parity sample so the proof tightens.
            if (parity) {
                throw AssertionError(
                    "$sampleName now renders at parity — remove it from KNOWN_DIVERGENT_SAMPLES " +
                        "(BUG #1 heading-drop / BUG #2 inline-code-backtick appears fixed).",
                )
            }
            // Still divergent as documented — skip loudly (visible as SKIPPED, never a false PASS).
            assumeTrue(
                "$sampleName diverges due to documented REAL renderer bug(s): native headings " +
                    "render empty (BUG #1) and/or native inline code keeps backticks (BUG #2). " +
                    "See class KDoc + parity report. NOT a test-harness issue — a renderer fix is " +
                    "required before markdownAst can flip on.",
                false,
            )
        }

        // Non-divergent sample: assert HARD parity.
        if (!parity) {
            throw AssertionError(buildParityDiff(sampleName, jvmNorm, nativeNorm))
        }
    }

    private fun String.normalizeImageAlt(): String =
        lines().joinToString("\n") { it.normalizeImageAltBrackets() }

    companion object {
        private val CORPUS_DIR = File(MARKDOWN_CORPUS_DIR)
        private const val TAG_JVM = "parity-jvm-tree"
        private const val TAG_NATIVE = "parity-native-tree"

        /**
         * Samples whose JVM-tree and native-tree renders diverge solely because of the two REAL
         * renderer bugs documented in the class KDoc (BUG #1 native-heading-drop, BUG #2
         * native-inline-code-backtick). Determined empirically from the dual-render diff: every
         * sample here contains a heading and/or inline code; the residual difference is exactly the
         * two bugs. These are SKIPPED (not failed, not passed) so the suite is green WITHOUT
         * pretending the native tree renders correctly — and the rot guard re-promotes any that get
         * fixed. The two truly-equal samples are NOT here:
         *  - `20-html-block` — `hasHtmlBlocks`, both engines route to the identical `MarkdownNew`
         *    HTML path, so the tree is bypassed (trivially equal, but a real datapoint: the HTML
         *    arm is parity-safe).
         *  - `30-empty-and-whitespace` — whitespace-only input, both render nothing.
         */
        private val KNOWN_DIVERGENT_SAMPLES: Set<String> = setOf(
            "01-plain-paragraphs",        // BUG #2 (inline code `<p>`)
            "02-headings-all-levels",     // BUG #1 + #2
            "03-emphasis-nesting",        // BUG #1 + #2
            "04-links-inline",            // BUG #1 + #2
            "05-links-with-titles",       // BUG #1
            "06-images",                  // BUG #1
            "07-fenced-code-kotlin",      // BUG #1 + #2
            "08-fenced-code-no-lang",     // BUG #1
            "09-indented-code",           // BUG #1
            "10-inline-code",             // BUG #1 + #2
            "11-gfm-table-simple",        // BUG #1 + #2
            "12-gfm-table-aligned",       // BUG #1 + #2
            "13-nested-lists",            // BUG #1 + #2
            "14-ordered-list-start",      // BUG #1 + #2
            "15-task-lists",              // BUG #1 + #2
            "16-blockquotes-nested",      // BUG #1 + #2
            "17-thematic-breaks",         // BUG #1 + #2
            "18-katex-inline",            // BUG #1 + #2
            "19-katex-block",             // BUG #1
            "21-inline-html",             // BUG #1 + #2
            "22-footnotes",               // BUG #1 + #2
            "23-strikethrough",           // BUG #1 + #2
            "24-cjk-mixed",               // BUG #1 + #2
            "25-long-message",            // BUG #1 + #2
            "26-streaming-truncated",     // BUG #1 + #2
            "27-hard-soft-breaks",        // BUG #1 + #2
            "28-link-edge-cases",         // BUG #1 + #2
            "29-mixed-everything",        // BUG #1 + #2
            "31-deep-nesting",            // BUG #1 + #2
            "32-special-chars-escapes",   // BUG #1 + #2
        )

        private fun blobFileFor(sampleName: String): File = File(CORPUS_DIR, "$sampleName.pmda")

        @JvmStatic
        @ParameterizedRobolectricTestRunner.Parameters(name = "{0}")
        fun samples(): List<Array<Any>> =
            CORPUS_DIR.listFiles { f -> f.extension == "md" }
                .orEmpty()
                // Only samples that have a paired golden blob can be compared tree-vs-tree.
                .filter { File(CORPUS_DIR, "${it.nameWithoutExtension}.pmda").exists() }
                .sortedBy { it.name }
                .map { arrayOf(it.nameWithoutExtension, it) }

        /**
         * ACCEPTED divergence #1 (image alt brackets). The dump renders image alt text as
         * `image=<contentDescription>`. The JVM tree's image alt is the RAW LINK_TEXT including the
         * surrounding `[ ]` (NativeMdTree.kt `linkLabel` KDoc: "the image-alt call site uses the
         * label as-is … native alt text lacks the brackets the JVM alt carries"). The bracket
         * presence is non-visible accessibility metadata, so we strip ONE leading `[` and ONE
         * trailing `]` from the alt segment of `image=` lines on both sides before comparison.
         */
        private fun String.normalizeImageAltBrackets(): String {
            val marker = "image="
            val idx = indexOf(marker)
            if (idx < 0) return this
            val prefix = substring(0, idx + marker.length)
            var alt = substring(idx + marker.length)
            if (alt.startsWith("[")) alt = alt.substring(1)
            if (alt.endsWith("]")) alt = alt.substring(0, alt.length - 1)
            return prefix + alt
        }

        /** Unified-ish diff between the two engines plus the first differing line. */
        private fun buildParityDiff(name: String, jvm: String, native: String): String {
            val j = jvm.lines()
            val n = native.lines()
            val firstDiff = (0 until maxOf(j.size, n.size)).firstOrNull {
                j.getOrNull(it) != n.getOrNull(it)
            }
            val pointer = if (firstDiff != null) {
                "\nfirst diff at line ${firstDiff + 1}:\n" +
                    "  jvm:    ${j.getOrNull(firstDiff)}\n" +
                    "  native: ${n.getOrNull(firstDiff)}"
            } else {
                ""
            }
            return buildString {
                appendLine("dual-tree render parity mismatch for sample '$name'")
                appendLine("(JVM JetBrains tree vs native packed-AST tree, same renderer, same raw input)")
                appendLine("If this is one of the two DOCUMENTED renderer bugs (native heading-drop /")
                appendLine("native inline-code-backtick), add '$name' to KNOWN_DIVERGENT_SAMPLES with a")
                appendLine("citation. If it is a NEW divergence, investigate the root cause first.")
                appendLine(pointer)
                appendLine("----- JVM TREE DUMP -----")
                appendLine(jvm)
                appendLine("----- NATIVE TREE DUMP -----")
                appendLine(native)
            }
        }
    }
}
