package app.amber.feature.board.hotlist.deepread.template

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.intOrNull
import app.amber.feature.board.hotlist.deepread.DeepReadSource
import java.net.URI

/**
 * Generation templates for topic syntheses beyond the shared magazine pipeline.
 * Port of iOS `DeepReadSynthesisTemplate` (DeepReadSynthesisTemplates.swift):
 * each one asks the model for a different content structure in a single call
 * over the collected sources; AUTO lets the model pick one first.
 */
enum class DeepReadSynthesisTemplate(val wireId: String) {
    AUTO("deepread_auto"),
    BRIEF("deepread_brief"),
    QA("deepread_qa"),
    DEBATE("deepread_debate"),
    TIMELINE("deepread_timeline"),
    REVIEW("deepread_review"),
    ;

    /** Templates the model may pick in auto mode (plus the classic magazine). */
    companion object {
        val CONCRETE: List<DeepReadSynthesisTemplate> = listOf(BRIEF, QA, DEBATE, TIMELINE, REVIEW)

        fun fromWireId(id: String): DeepReadSynthesisTemplate? =
            entries.firstOrNull { it.wireId == id }
    }
}

/**
 * A topic synthesis generated by one of [DeepReadSynthesisTemplate], stored in
 * `deep_read_cache.structured_json` under its own `shape`. Field names mirror the
 * iOS `DeepReadTemplateArticle` JSON so stored payloads stay cross-platform.
 */
@Serializable
data class DeepReadTemplateArticle(
    val shape: String = SHAPE_ID,
    val template: String = "",
    val title: String = "",
    val lede: String = "",
    val sources: List<Source> = emptyList(),
    val brief: Brief? = null,
    val qa: List<Answer>? = null,
    val debate: Debate? = null,
    val timeline: Timeline? = null,
    val review: Review? = null,
) {
    @Serializable
    data class Source(
        val id: Int,
        val title: String,
        val url: String? = null,
        val site: String = "",
    )

    @Serializable
    data class Brief(
        val points: List<String> = emptyList(),
        val background: String = "",
        val impact: String = "",
        val uncertain: List<String> = emptyList(),
    )

    @Serializable
    data class Answer(
        val question: String = "",
        val answer: String = "",
        val sources: List<Int> = emptyList(),
    )

    @Serializable
    data class Debate(
        val dispute: String = "",
        val camps: List<Camp> = emptyList(),
        val takeaway: String = "",
    ) {
        @Serializable
        data class Camp(
            val stance: String = "neutral",
            val label: String = "",
            val holders: List<String> = emptyList(),
            val argument: String = "",
            val quote: String = "",
            val quoteBy: String = "",
            val sources: List<Int> = emptyList(),
        )
    }

    @Serializable
    data class Timeline(
        val events: List<Event> = emptyList(),
        val turns: List<Turn> = emptyList(),
    ) {
        @Serializable
        data class Event(
            val date: String = "",
            val event: String = "",
            val turning: Boolean = false,
            val sources: List<Int> = emptyList(),
        )

        @Serializable
        data class Turn(
            val date: String = "",
            val why: String = "",
        )
    }

    @Serializable
    data class Review(
        val verdict: String = "",
        val consensus: List<String> = emptyList(),
        val splits: List<Split> = emptyList(),
        val specs: List<Spec> = emptyList(),
        val scores: List<Score> = emptyList(),
        val conclusion: String = "",
    ) {
        @Serializable
        data class Split(
            val topic: String = "",
            val views: List<View> = emptyList(),
        )

        @Serializable
        data class View(
            val source: Int = 0,
            val view: String = "",
        )

        @Serializable
        data class Spec(
            val name: String = "",
            val value: String = "",
        )

        @Serializable
        data class Score(
            val source: Int = 0,
            val score: String = "",
            val note: String = "",
        )
    }

    val kind: DeepReadSynthesisTemplate
        get() = DeepReadSynthesisTemplate.fromWireId(template) ?: DeepReadSynthesisTemplate.BRIEF

    fun encoded(json: Json = JsonInstant): String? =
        runCatching { json.encodeToString(serializer(), this) }.getOrNull()

    companion object {
        const val SHAPE_ID = "template_synthesis"

        private val JsonInstant = Json {
            ignoreUnknownKeys = true
            encodeDefaults = true
        }

        fun decode(raw: String?): DeepReadTemplateArticle? {
            if (raw.isNullOrBlank()) return null
            return runCatching { JsonInstant.decodeFromString<DeepReadTemplateArticle>(raw) }
                .getOrNull()
                ?.takeIf { it.shape == SHAPE_ID }
        }
    }
}

/** Prompts, parsing and markdown export for synthesis templates — iOS `DeepReadTemplateWriter` parity. */
object DeepReadSynthesisWriter {
    const val MAX_SOURCES = 12
    const val EXCERPT_CHARS = 1_200

    /** Auto mode may also keep the classic magazine pipeline. */
    const val MAGAZINE_CHOICE = "magazine"

    fun numbered(sources: List<DeepReadSource>): List<NumberedSource> =
        sources.filter { it.hasUsableGenerationContent() }
            .take(MAX_SOURCES)
            .mapIndexed { index, source -> NumberedSource(index + 1, source) }

    data class NumberedSource(val id: Int, val source: DeepReadSource)

    private fun sourcesBlock(numbered: List<NumberedSource>): String =
        numbered.joinToString("\n\n") { item ->
            val site = siteName(item.source.url) ?: item.source.source.orEmpty()
            "[${item.id}] $site｜${item.source.title}\n" +
                cleanMultiline(item.source.content).take(EXCERPT_CHARS)
        }

    // MARK: Auto pick

    fun pickPrompt(topic: String, numbered: List<NumberedSource>): String {
        val b = StringBuilder()
        b.append("你要为话题「$topic」选择最合适的深度阅读写法。只看下面的来源标题和开头，不要写文章。\n## 可选\n")
        for (template in DeepReadSynthesisTemplate.CONCRETE) {
            b.append("- ${template.wireId}：${template.displayNameZh}，适合${template.useWhen}\n")
        }
        b.append("- $MAGAZINE_CHOICE：经典杂志长文，适合背景复杂、需要全面梳理时间线与各方分析的重大事件\n")
        b.append("""只输出 JSON：{"template":"deepread_brief","reason":"一句话理由"}""")
        b.append("\n\n## 来源\n")
        b.append(
            numbered.joinToString("\n") {
                "[${it.id}] ${it.source.title}：${cleanMultiline(it.source.content).take(160)}"
            },
        )
        return b.toString()
    }

    /** The chosen template, or null for the classic magazine (also the fallback for an unreadable reply). */
    fun parsePick(text: String): DeepReadSynthesisTemplate? {
        val json = extractJsonObject(text) ?: return null
        val element = runCatching { Json.parseToJsonElement(json) }.getOrNull() as? JsonObject
            ?: return null
        val id = (element["template"] as? JsonPrimitive)?.content?.trim() ?: return null
        return DeepReadSynthesisTemplate.fromWireId(id)?.takeIf { it != DeepReadSynthesisTemplate.AUTO }
    }

    // MARK: Generate

    fun prompt(
        template: DeepReadSynthesisTemplate,
        topic: String,
        numbered: List<NumberedSource>,
    ): String {
        val b = StringBuilder()
        b.append("你是深度阅读的编辑，要用「${template.displayNameZh}」的写法，把下面的来源整理成一篇关于「$topic」的中文深度阅读。\n")
        b.append("## 通用要求\n- title：简体中文标题，不超过 30 字。\n- lede：80-160 字导语。\n")
        b.append("- 只用来源里的事实，不编造；sources 填来源编号数组，用来标注依据。\n- 所有文字用简体中文。只输出合法 JSON，不要代码围栏和解释。\n")
        b.append("## 模板要求\n")
        when (template) {
            DeepReadSynthesisTemplate.AUTO, DeepReadSynthesisTemplate.BRIEF -> {
                b.append("points 5 条要点，每条不超过 50 字；background 背景 100-200 字；impact 影响 100-200 字；uncertain 0-4 条尚未确认的说法，每条不超过 60 字。\n")
                b.append("""输出：{"title":"…","lede":"…","points":["…"],"background":"…","impact":"…","uncertain":["…"]}""")
            }
            DeepReadSynthesisTemplate.QA -> {
                b.append("questions 5-8 个读者最可能问的问题，由浅入深；q 不超过 30 字，a 80-220 字，sources 为依据的来源编号。\n")
                b.append("""输出：{"title":"…","lede":"…","questions":[{"q":"…","a":"…","sources":[1,2]}]}""")
            }
            DeepReadSynthesisTemplate.DEBATE -> {
                b.append("dispute 核心争议不超过 80 字；camps 2-4 个阵营，stance 取 pro（支持）、con（反对）、neutral（中立或折中）；label 阵营名不超过 10 字，holders 代表人物或机构不超过 4 个，argument 主要论点不超过 160 字，quote 来源中的一句原话（没有就空字符串），quote_by 说话人，sources 来源编号；takeaway「你可以怎么看」不超过 160 字，帮读者权衡而不是替读者站队。\n")
                b.append("""输出：{"title":"…","lede":"…","dispute":"…","camps":[{"stance":"pro","label":"…","holders":["…"],"argument":"…","quote":"…","quote_by":"…","sources":[1]}],"takeaway":"…"}""")
            }
            DeepReadSynthesisTemplate.TIMELINE -> {
                b.append("events 10-15 个时间节点，按时间先后；date 写具体日期或时间，event 不超过 60 字，turning 标记是否为转折点（总共 1-3 个），sources 来源编号；turns 解读每个转折点，why 不超过 120 字。\n")
                b.append("""输出：{"title":"…","lede":"…","events":[{"date":"…","event":"…","turning":false,"sources":[1]}],"turns":[{"date":"…","why":"…"}]}""")
            }
            DeepReadSynthesisTemplate.REVIEW -> {
                b.append("verdict 一句话总结论不超过 60 字；consensus 各家共识 3-5 条，每条不超过 40 字；splits 1-4 个分歧点，topic 不超过 10 字，views 为各来源的看法 {source 编号, view 不超过 40 字}；specs 3-8 行关键规格 {name, value}；scores 各家打分 {source 编号, score 原样写出如「4/5」「8.5」, note 不超过 20 字}，没有打分就空数组；conclusion 买不买的建议不超过 160 字。\n")
                b.append("""输出：{"title":"…","lede":"…","verdict":"…","consensus":["…"],"splits":[{"topic":"…","views":[{"source":1,"view":"…"}]}],"specs":[{"name":"…","value":"…"}],"scores":[{"source":1,"score":"…","note":"…"}],"conclusion":"…"}""")
            }
        }
        b.append("\n\n## 来源\n").append(sourcesBlock(numbered))
        return b.toString()
    }

    fun parse(
        text: String,
        template: DeepReadSynthesisTemplate,
        topic: String,
        numbered: List<NumberedSource>,
    ): DeepReadTemplateArticle? {
        val json = extractJsonObject(text) ?: repairTruncatedJson(text) ?: return null
        val obj = runCatching { Json.parseToJsonElement(json) }.getOrNull() as? JsonObject
            ?: return null
        val ids = numbered.map { it.id }.toSet()

        fun string(key: String): String =
            (obj[key] as? JsonPrimitive)?.content?.trim().orEmpty()

        fun stringsOf(key: String, limit: Int): List<String> =
            (obj[key] as? JsonArray).orEmpty()
                .map { (it as? JsonPrimitive)?.content?.trim().orEmpty() }
                .filter { it.isNotEmpty() }
                .take(limit)

        fun objectsOf(key: String): List<JsonObject> =
            (obj[key] as? JsonArray).orEmpty().mapNotNull { it as? JsonObject }

        fun JsonObject.string(key: String): String =
            (this[key] as? JsonPrimitive)?.content?.trim().orEmpty()

        fun JsonObject.int(key: String): Int? = when (val v = this[key]) {
            is JsonPrimitive -> v.intOrNull
                ?: v.content.toDoubleOrNull()?.let { kotlin.math.round(it).toInt() }
                ?: v.content.toIntOrNull()
            else -> null
        }

        fun JsonObject.cited(key: String): List<Int> =
            (this[key] as? JsonArray).orEmpty()
                .mapNotNull { (it as? JsonPrimitive)?.intOrNull ?: (it as? JsonPrimitive)?.content?.toIntOrNull() }
                .filter { ids.contains(it) }

        val article = DeepReadTemplateArticle(
            template = (if (template == DeepReadSynthesisTemplate.AUTO) DeepReadSynthesisTemplate.BRIEF else template).wireId,
            title = string("title").ifEmpty { topic },
            lede = string("lede"),
            sources = numbered.map { item ->
                DeepReadTemplateArticle.Source(
                    id = item.id,
                    title = item.source.title,
                    url = item.source.url.takeIf { it.isNotBlank() },
                    site = siteName(item.source.url) ?: item.source.source.orEmpty(),
                )
            },
        )
        return when (template) {
            DeepReadSynthesisTemplate.AUTO, DeepReadSynthesisTemplate.BRIEF -> {
                val points = stringsOf("points", 5)
                if (points.isEmpty()) return null
                article.copy(
                    brief = DeepReadTemplateArticle.Brief(
                        points = points,
                        background = string("background"),
                        impact = string("impact"),
                        uncertain = stringsOf("uncertain", 4),
                    ),
                )
            }
            DeepReadSynthesisTemplate.QA -> {
                val answers = objectsOf("questions").mapNotNull { raw ->
                    val q = raw.string("q")
                    val a = raw.string("a")
                    if (q.isEmpty() || a.isEmpty()) null
                    else DeepReadTemplateArticle.Answer(q, a, raw.cited("sources"))
                }.take(8)
                if (answers.isEmpty()) return null
                article.copy(qa = answers)
            }
            DeepReadSynthesisTemplate.DEBATE -> {
                val camps = objectsOf("camps").mapNotNull { raw ->
                    val argument = raw.string("argument")
                    if (argument.isEmpty()) return@mapNotNull null
                    val stance = raw.string("stance").takeIf { it in setOf("pro", "con", "neutral") } ?: "neutral"
                    DeepReadTemplateArticle.Debate.Camp(
                        stance = stance,
                        label = raw.string("label"),
                        holders = (raw["holders"] as? JsonArray).orEmpty()
                            .mapNotNull { (it as? JsonPrimitive)?.content?.trim() }
                            .filter { it.isNotEmpty() }
                            .take(4),
                        argument = argument,
                        quote = raw.string("quote"),
                        quoteBy = raw.string("quote_by"),
                        sources = raw.cited("sources"),
                    )
                }.take(4)
                if (camps.size < 2) return null
                article.copy(
                    debate = DeepReadTemplateArticle.Debate(
                        dispute = string("dispute"),
                        camps = camps,
                        takeaway = string("takeaway"),
                    ),
                )
            }
            DeepReadSynthesisTemplate.TIMELINE -> {
                val events = objectsOf("events").mapNotNull { raw ->
                    val event = raw.string("event")
                    if (event.isEmpty()) return@mapNotNull null
                    DeepReadTemplateArticle.Timeline.Event(
                        date = raw.string("date"),
                        event = event,
                        turning = (raw["turning"] as? JsonPrimitive)?.booleanOrNull
                            ?: raw.string("turning").equals("true", ignoreCase = true),
                        sources = raw.cited("sources"),
                    )
                }.take(15)
                if (events.size < 3) return null
                val turns = objectsOf("turns").mapNotNull { raw ->
                    val why = raw.string("why")
                    if (why.isEmpty()) null else DeepReadTemplateArticle.Timeline.Turn(raw.string("date"), why)
                }.take(3)
                article.copy(
                    timeline = DeepReadTemplateArticle.Timeline(events = events, turns = turns),
                )
            }
            DeepReadSynthesisTemplate.REVIEW -> {
                val verdict = string("verdict")
                if (verdict.isEmpty()) return null
                val splits = objectsOf("splits").mapNotNull { raw ->
                    val views = (raw["views"] as? JsonArray).orEmpty().mapNotNull { view ->
                        val v = view as? JsonObject ?: return@mapNotNull null
                        val source = v.int("source") ?: return@mapNotNull null
                        val viewText = v.string("view")
                        if (!ids.contains(source) || viewText.isEmpty()) return@mapNotNull null
                        DeepReadTemplateArticle.Review.View(source, viewText)
                    }
                    val topicName = raw.string("topic")
                    if (topicName.isEmpty() || views.isEmpty()) null
                    else DeepReadTemplateArticle.Review.Split(topicName, views)
                }.take(4)
                val specs = objectsOf("specs").mapNotNull { raw ->
                    val name = raw.string("name")
                    val value = raw.string("value")
                    if (name.isEmpty() || value.isEmpty()) null
                    else DeepReadTemplateArticle.Review.Spec(name, value)
                }.take(8)
                val scores = objectsOf("scores").mapNotNull { raw ->
                    val source = raw.int("source") ?: return@mapNotNull null
                    val score = raw.string("score")
                    if (!ids.contains(source) || score.isEmpty()) return@mapNotNull null
                    DeepReadTemplateArticle.Review.Score(source, score, raw.string("note"))
                }
                article.copy(
                    review = DeepReadTemplateArticle.Review(
                        verdict = verdict,
                        consensus = stringsOf("consensus", 5),
                        splits = splits,
                        specs = specs,
                        scores = scores,
                        conclusion = string("conclusion"),
                    ),
                )
            }
        }
    }

    // MARK: Export

    fun markdown(article: DeepReadTemplateArticle): String {
        fun refs(ids: List<Int>): String =
            if (ids.isEmpty()) "" else " " + ids.joinToString("") { "[$it]" }

        fun bullets(items: List<String>): String =
            items.joinToString("") { "- $it\n" } + "\n"

        val b = StringBuilder("# ${article.title}\n\n")
        if (article.lede.isNotEmpty()) b.append("> ${article.lede}\n\n")
        article.brief?.let { brief ->
            b.append("## 要点\n").append(bullets(brief.points))
            if (brief.background.isNotEmpty()) b.append("## 背景\n\n${brief.background}\n\n")
            if (brief.impact.isNotEmpty()) b.append("## 影响\n\n${brief.impact}\n\n")
            if (brief.uncertain.isNotEmpty()) b.append("## 待核实\n").append(bullets(brief.uncertain))
        }
        article.qa?.forEach { item ->
            b.append("## ${item.question}\n\n${item.answer}${refs(item.sources)}\n\n")
        }
        article.debate?.let { debate ->
            if (debate.dispute.isNotEmpty()) b.append("## 核心争议\n\n${debate.dispute}\n\n")
            debate.camps.forEach { camp ->
                b.append("### ${camp.label}")
                if (camp.holders.isNotEmpty()) b.append("（${camp.holders.joinToString("、")}）")
                b.append("\n\n${camp.argument}${refs(camp.sources)}\n\n")
                if (camp.quote.isNotEmpty()) {
                    b.append("> “${camp.quote}”")
                    if (camp.quoteBy.isNotEmpty()) b.append(" —— ${camp.quoteBy}")
                    b.append("\n\n")
                }
            }
            if (debate.takeaway.isNotEmpty()) b.append("## 你可以怎么看\n\n${debate.takeaway}\n\n")
        }
        article.timeline?.let { timeline ->
            b.append("## 时间线\n").append(
                bullets(
                    timeline.events.map {
                        "**${it.date}**${if (it.turning) "（转折）" else ""} ${it.event}${refs(it.sources)}"
                    },
                ),
            )
            if (timeline.turns.isNotEmpty()) {
                b.append("## 转折点\n").append(bullets(timeline.turns.map { "**${it.date}** ${it.why}" }))
            }
        }
        article.review?.let { review ->
            b.append("## 结论\n\n**${review.verdict}**\n\n")
            if (review.consensus.isNotEmpty()) b.append("## 各家共识\n").append(bullets(review.consensus))
            review.splits.forEach { split ->
                b.append("## 分歧：${split.topic}\n").append(
                    bullets(split.views.map { "[${it.source}] ${it.view}" }),
                )
            }
            if (review.specs.isNotEmpty()) {
                b.append("## 关键规格\n").append(bullets(review.specs.map { "${it.name}：${it.value}" }))
            }
            if (review.scores.isNotEmpty()) {
                b.append("## 打分\n").append(
                    bullets(review.scores.map { "[${it.source}] ${it.score}${if (it.note.isEmpty()) "" else "（${it.note}）"}" }),
                )
            }
            if (review.conclusion.isNotEmpty()) b.append("## 买不买\n\n${review.conclusion}\n\n")
        }
        b.append("## 来源\n").append(
            bullets(
                article.sources.map { source ->
                    "[${source.id}] ${source.site}：" +
                        (source.url?.let { "[${source.title}]($it)" } ?: source.title)
                },
            ),
        )
        return b.toString()
    }

    // MARK: Helpers

    fun siteName(url: String): String? {
        val host = runCatching { URI(url).host }.getOrNull() ?: return null
        return host.removePrefix("www.").takeIf { it.isNotBlank() }
    }

    // iOS hasUsableGenerationContent parity on the enriched projection: scrape
    // status was already filtered upstream; reject empty bodies and search rows
    // whose "content" never resolved past the URL itself.
    private fun DeepReadSource.hasUsableGenerationContent(): Boolean =
        content.isNotBlank() && content.trim() != url.trim()

    private fun cleanMultiline(text: String): String =
        text.lines().map { it.trim() }.filter { it.isNotEmpty() }.joinToString("\n")

    /// First balanced top-level {...} object (ignores braces inside strings), so a
    /// response wrapped in ```json fences or surrounding prose still parses.
    /// iOS `IOSDeepReadDraftGenerator.extractJSONObject` parity.
    internal fun extractJsonObject(text: String): String? {
        val start = text.indexOf('{')
        if (start < 0) return null
        var depth = 0
        var inString = false
        var escaped = false
        for (i in start until text.length) {
            val c = text[i]
            if (inString) {
                when {
                    escaped -> escaped = false
                    c == '\\' -> escaped = true
                    c == '"' -> inString = false
                }
            } else when (c) {
                '"' -> inString = true
                '{' -> depth += 1
                '}' -> {
                    depth -= 1
                    if (depth == 0) return text.substring(start, i + 1)
                }
            }
        }
        return null
    }

    /// Close an unterminated JSON document by trimming dangling commas before each
    /// closer. iOS `IOSDeepReadDraftGenerator.repairTruncatedJSON` parity.
    private fun repairTruncatedJson(text: String): String? {
        val start = text.indexOf('{')
        if (start < 0) return null
        val stack = ArrayDeque<Char>()
        var inString = false
        var escaped = false
        for (i in start until text.length) {
            val c = text[i]
            if (inString) {
                when {
                    escaped -> escaped = false
                    c == '\\' -> escaped = true
                    c == '"' -> inString = false
                }
            } else when (c) {
                '"' -> inString = true
                '{' -> stack.addLast('}')
                '}' -> if (stack.lastOrNull() == '}') stack.removeLast()
                '[' -> stack.addLast(']')
                ']' -> if (stack.lastOrNull() == ']') stack.removeLast()
            }
        }
        if (!inString && stack.isEmpty()) return null
        var body = text.substring(start)
        val suffix = StringBuilder()
        if (inString) suffix.append('"')
        while (stack.isNotEmpty()) {
            body = body.trimEnd()
            if (body.lastOrNull() == ',') body = body.dropLast(1)
            suffix.append(stack.removeLast())
        }
        return body + suffix
    }
}

/** Canonical Chinese display name — iOS `DeepReadSynthesisTemplate.name` (prompts + messages). */
val DeepReadSynthesisTemplate.displayNameZh: String
    get() = when (this) {
        DeepReadSynthesisTemplate.AUTO -> "自动"
        DeepReadSynthesisTemplate.BRIEF -> "速览简报"
        DeepReadSynthesisTemplate.QA -> "问答解读"
        DeepReadSynthesisTemplate.DEBATE -> "观点交锋"
        DeepReadSynthesisTemplate.TIMELINE -> "时间线报道"
        DeepReadSynthesisTemplate.REVIEW -> "评测汇总"
    }

private val DeepReadSynthesisTemplate.useWhen: String
    get() = when (this) {
        DeepReadSynthesisTemplate.AUTO -> ""
        DeepReadSynthesisTemplate.BRIEF -> "一般新闻，读者只想快速了解"
        DeepReadSynthesisTemplate.QA -> "政策、新技术、规则变化或复杂事件，读者有很多疑问"
        DeepReadSynthesisTemplate.DEBATE -> "存在明显争议、多方立场对立"
        DeepReadSynthesisTemplate.TIMELINE -> "持续发酵、有多个时间节点的事件"
        DeepReadSynthesisTemplate.REVIEW -> "新产品或服务发布，有多家评测"
    }
